### ISSUE TITLE
Plugin crashed after attempting to refit a peak with a different FWHM

### ISSUE THREAD

**Issue by davidgirata** [rickud/gel-lanes-fit#7]
[INFO] Gel Lanes Fit
[INFO] Gel Lanes Fit 1.0.5
[INFO] Loading gel-lanes-fit\data\2019_6_19\saved-state.bak ...
[INFO] Could not find previously saved state
[INFO] Loading gel-lanes-fit\data\2019_6_19\saved-state.bak ...
[INFO] Could not find previously saved state
[INFO] Saving to gel-lanes-fit\data\2019_6_19\saved-state.bak ...
[INFO] Saving to gel-lanes-fit\data\2019_6_19\saved-state.bak ...
[INFO] Saving to gel-lanes-fit\data\2019_6_19\saved-state.bak ...
[INFO] Lane 1, RMS: 0.0606; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 11, RMS: 0.0846; 
[INFO] Lane 5, RMS: 0.1870; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Lane 7, RMS: 0.2116; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 2, RMS: 0.0613; 
[INFO] Time elapsed: 0.1 s

[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 1, RMS: 0.0804; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 1, RMS: 0.0804; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 1, RMS: 0.0606; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 11, RMS: 0.0846; 
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 7, RMS: 0.2116; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 2, RMS: 0.0613; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Lane 5, RMS: 0.1870; 
[INFO] Time elapsed: 0.1 s

[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 1, RMS: 0.0591; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 11, RMS: 0.0766; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 2, RMS: 0.0594; 
[INFO] Lane 7, RMS: 0.2116; 
[INFO] Lane 5, RMS: 0.1870; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Time elapsed: 0.1 s

[INFO] Size mismatch: 0, 3
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 1, RMS: 0.0804; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Custom Peak added: 1, 3384.265662881204, 599.9349240780911
[INFO] Lane 1, RMS: 0.0733; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 11, RMS: 0.0766; 
[INFO] Lane 7, RMS: 0.2116; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 5, RMS: 0.2111; 
[INFO] Lane 2, RMS: 0.0594; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Time elapsed: 0.1 s

[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 1, RMS: 0.0733; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 11, RMS: 0.0766; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 7, RMS: 0.2116; 
[INFO] Lane 5, RMS: 0.2111; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 2, RMS: 0.0594; 
[INFO] Time elapsed: 0.1 s

[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Custom Peak added: 5, 3248.079335204798, 585.175704989154
[INFO] Lane 1, RMS: 0.0733; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Lane 11, RMS: 0.0766; 
[INFO] Lane 2, RMS: 0.0594; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 5, RMS: 0.2170; 
[INFO] Lane 7, RMS: 0.2116; 
[INFO] Time elapsed: 0.1 s

[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 1, RMS: 0.0733; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 11, RMS: 0.0766; 
[INFO] Lane 7, RMS: 0.2116; 
[INFO] Lane 5, RMS: 0.2111; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Lane 2, RMS: 0.0594; 
[INFO] Time elapsed: 0.1 s

[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 1, RMS: 0.0733; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 11, RMS: 0.0846; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 5, RMS: 0.2111; 
[INFO] Lane 7, RMS: 0.2116; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 2, RMS: 0.0613; 
[INFO] Time elapsed: 0.1 s

[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Custom Peak not added: 7, 3271.859512568585, 704.8893709327549
[INFO] Custom Peak added: 7, 3281.2641316830413, 705.7093275488069
[INFO] Lane 1, RMS: 0.0733; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] [LANE 7] Peak guess: 279.1323529411766, 706.0, 25.479654008640573
[INFO] 		Replaced with: 3281.2641316830413, 705.7093275488069, 6.369913502160143
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 11, RMS: 0.0846; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 7, RMS: 0.2426; 
[INFO] Lane 5, RMS: 0.2111; 
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 2, RMS: 0.0613; 
[INFO] Time elapsed: 0.1 s

[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] Custom Peak added: 5, 3249.8419994896008, 586.8156182212581
[INFO] Lane 1, RMS: 0.0733; 
[INFO] Saving to gel-lanes-fit\data\2019_6_19\Fit of 2019_6_19 Melted, TOPO II, Labeled plasmids.xls ...
[INFO] [LANE 7] Peak guess: 279.1323529411766, 706.0, 25.479654008640573
[INFO] 		Replaced with: 3281.2641316830413, 705.7093275488069, 6.369913502160143
[INFO] Lane 3, RMS: 0.1494; 
[INFO] Lane 8, RMS: 0.1075; 
[INFO] Lane 10, RMS: 0.1382; 
[INFO] Lane 11, RMS: 0.0846; 
[INFO] [LANE 5] Peak guess: 296.5588235294117, 588.0, 19.53440140662444
[INFO] 		Replaced with: 3249.8419994896008, 586.8156182212581, 5.095930801728114
[INFO] Lane 6, RMS: 0.1328; 
[INFO] Lane 12, RMS: 0.0861; 
[INFO] Lane 4, RMS: 0.1882; 
[INFO] Lane 7, RMS: 0.2426; 
[INFO] Lane 9, RMS: 0.1551; 
[INFO] Lane 2, RMS: 0.0613; 
[INFO] Lane 5, RMS: 0.2465; 
[INFO] Time elapsed: 0.1 s

[INFO] Size mismatch: 3, 0
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at gellanesfit.Fitter.updateResultsTable(Fitter.java:147)
	at gellanesfit.MainDialog.actionPerformed(MainDialog.java:1460)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by davidgirata** [comment]
Plug in came back after "fit" was clicked again. but it is good to note this issue
