### ISSUE TITLE
Plugin failed to start

### ISSUE THREAD

**Issue by trexol** [rickud/gel-lanes-fit#9]
The install seems to proceed correctly, but when i try to start the plugin, FIJI returns both:

- The following exception window:
(Fiji Is Just) ImageJ 2.0.0-rc-43/1.52n; Java 1.6.0_24 [64-bit]; Linux 3.13.0-40-generic; 13MB of 5601MB (<1%)
 
java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:270)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:161)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:662)

- The following console:
[ERROR] Cannot create module: gellanesfit.GelLanesFit
org.scijava.module.ModuleException: org.scijava.InstantiableException: Class not found: gellanesfit.GelLanesFit
	at org.scijava.command.CommandInfo.createModule(CommandInfo.java:320)
	at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:156)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:195)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:186)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:171)
	at org.scijava.command.DefaultCommandService.run(DefaultCommandService.java:185)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:270)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:161)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.scijava.InstantiableException: Class not found: gellanesfit.GelLanesFit
	at org.scijava.plugin.PluginInfo.loadClass(PluginInfo.java:285)
	at org.scijava.command.CommandInfo.loadClass(CommandInfo.java:245)
	at org.scijava.command.CommandInfo.createModule(CommandInfo.java:314)
	... 11 more

Any idea?

**Comment by rickud** [comment]
I have not seen this error yet. Could be be some missing Fiji package? Is Java8 active in the update sites?
